### ISSUE TITLE
What Should I Get?

### ISSUE THREAD

**Issue by akatch** [akatch/hammerbros#15]
Create a new page of equipment needs and recommendations for new blacksmiths across multiple budgets.

**Comment by greenbagels** [comment]
> This page should include links to Black Bear Forge's affordable tools videos [1](https://www.youtube.com/watch?v=WHpWpdOBG_4) | [2](https://www.youtube.com/watch?v=o_cK7UqQcYI)

I think there should also be a sponsorship disclaimer (not that I don't trust BBF's reviews of Vevor tools, but that there could be tools such as the Doyle anvil that didn't get reviewed, potentially for that reason).

**Comment by TijlAerts** [comment]
Agreed with Greenbagels here. 
Looks like vevor sent him the tools free of charge so they would also carefully pick out one of their best anvils for those reviews etc. 

But they are good videos to add.

**Comment by akatch** [comment]
Fixed in #23
