### ISSUE TITLE
Reference the new Harbor Freight red cast steel anvil on the Equipment page

### ISSUE THREAD

**Issue by akatch** [akatch/hammerbros#18]
We've had a number of users ask about Harbor Freight's new cast steel anvil, which seems to be a reasonably good option for newbies. Let's include it on the equipment recommendations pages.

**Comment by TijlAerts** [comment]
With the limited amount of reviews out there it looks like it'll outperform the vevor ones for a similar $/lb.
So i would for sure include it into the recommendations pages.
